name: Issue rescans to VirusTotal.
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * sun'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
    - name: Update repo
      run: git pull origin main
    - name: Create .vt_key
      run: echo "${{ secrets.VIRUSTOTALKEY }}" > .vt_key
    - name: Run a one-line script
      run: nimble run rescan